### PR TITLE
Four additions

### PR DESCRIPTION
**Pull request by JonathanJTech**
Added Divine Blessing in Painting Guardian room
Clarified green titanite shards in Lost Izalith (There is one after the Demon Firesage, and also one after the Giant Centipede)
Added Marvelous Chester invasion in Oolacile

### CODE REVIEW

**Comment by JonathanJTech** [comment]
Added Crystal Lizard in Oolacile Township, near the mimic.

**Comment by IrishStevo** [comment]
Thanks Jon!

Can you make a couple of changes:

- To stay consistent can you change all the URLs you added to point to the Fextralife wiki rather than the Wikidot wiki.
- Can you change the data-id for `playthrough_11_6_0` to `playthrough_11_42`. When adding new items to a section you want to give it an ID that doesn't already exist and also keeps to the `playthrough_X_Y` format. `playthrough_11_41` is the maximum one used so far in section 11. The `playthrough_X_Y_Z` format is only used to indent items.
- Don't change any existing data-id values or it will break it for users who have already checked an item off. So change `playthrough_25_4_0` back to `playthrough_25_5`. And then for the same reasons as the previous note change your `playthrough_25_5` to `playthrough_25_17` and `playthrough_25_5_0` to `playthrough_25_18`.

Hopefully that explains the format I used a bit better. If you can make those changes I'll take another look.

**Comment by smcnabb** [comment]
(Commenting with the correct account this time!)

Thanks Jon!

Can you make a couple of changes:

- To stay consistent can you change all the URLs you added to point to the Fextralife wiki rather than the Wikidot wiki.
- Can you change the data-id for `playthrough_11_6_0` to `playthrough_11_42`. When adding new items to a section you want to give it an ID that doesn't already exist and also keeps to the `playthrough_X_Y` format. `playthrough_11_41` is the maximum one used so far in section 11. The `playthrough_X_Y_Z` format is only used to indent items.
- Don't change any existing data-id values or it will break it for users who have already checked an item off. So change `playthrough_25_4_0` back to `playthrough_25_5`. And then for the same reasons as the previous note change your `playthrough_25_5` to `playthrough_25_17` and `playthrough_25_5_0` to `playthrough_25_18`.

Hopefully that explains the format I used a bit better. If you can make those changes I'll take another look.

**Comment by JonathanJTech** [comment]
Okay, I have made the changes, except for changing `playthrough_25_4_0` to `playthrough_25_5`. My reasoning for this is because I feel that both the old and new `playthrough_25_5` mainly refer to the mimic, 'Very Good' carving, and killing the bloathead from range. Whereas what used to be `playthrough_25_4_0` (which is now `playthrough_25_17`) refers to being invaded by Marvelous Chester. Let me know what you think; I can reorder the numberings if you still would prefer it a certain way.

Other than that, I changed all of the links to direct to fextralife. Hopefully I didn't miss any. Please do take another look!

**Comment by smcnabb** [comment]
Looks good. Merged. Thanks again!

**Pull request merged**
